# myName = input("What's you name?: ")
# myAge = input("How old are you? :")
# print("Gee, that's REALLY OLD")
# replit = input("Do you like Replit?")
# print("OF COURSE YOU DO!")

# print()
# print("So, you are")
# print(myName)
# print("and are the ripe old age of")
# print(myAge)
# print("and clearly think that Replit is")
# print(replit)

# myVariable = input("WHO GOES THERE? ")
# print(myVariable)
# myGrandma = input("How's your Grandma doing? 😘 ")
# print(myGrandma)

# myLunch = input("What are you having for lunch? ")
# print("Hmm, it sounds like you really should just order")
# print(myLunch)
# print("as soon as possible!")

# print("Definitely not a Phishing Scam")
# print()
# input("What is your Name? ")
# print("Thanks for logging in")
# print(myName)
# cardNumber = input("What is your credit card number? ")
# print("Thanks, I definitely wont put")
# print(cardNumber)
# print("into Amazon and order anything weird")
# print()
# print("Promise")
# maidenName = input("What is your Mother's maiden name? ")
# print()
# print("That's cool, I just wanted to know that")
# print(maidenName)
# print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")

print("Getting to know you!")

name = input("What is your name? ")
favoriteFood = input("What is your favorite food? ")
favoriteMusic = input("What is your favorite music? ")
location = input("Where do you live? ")

print("You are")
print(name)
print("You are probably hungry for")
print(favoriteFood)
print("and you're definitely getting your groove on to")
print(favoriteMusic)
print("living in the amazing")
print(location)
